from __future__ import annotations

from typing import List, Dict


SEED_MOMENTS: List[Dict[str, object]] = [
    # Point A (太古里-春熙路) 30.6570, 104.0800
    {
        "title": "在这儿停一下",
        "audio_text": "我就站一会儿，风挺舒服的。",
        "mood_code": "healing",
        "lat": 30.6570,
        "lng": 104.0800,
        "motion_template_id": "T02_Cloud",
        "pony": False,
    },
    {
        "title": "今天别太用力",
        "audio_text": "慢一点也没关系，真的。",
        "mood_code": "tired",
        "lat": 30.6570,
        "lng": 104.0800,
        "motion_template_id": "T04_LightLeak",
        "pony": False,
    },
    {
        "title": "刚好看到一束光",
        "audio_text": "这一秒有点像礼物，我收下了。",
        "mood_code": "luck",
        "lat": 30.6570,
        "lng": 104.0800,
        "motion_template_id": "T04_LightLeak",
        "pony": False,
    },
    {
        "title": "我来了（马年）",
        "audio_text": "马年到啦，愿你一路向前也一路平安。",
        "mood_code": "healing",
        "lat": 30.6570,
        "lng": 104.0800,
        "motion_template_id": "T07_Sparkle",
        "pony": True,
    },
    {
        "title": "不想解释",
        "audio_text": "我没事，只是有点累，先放这儿。",
        "mood_code": "tired",
        "lat": 30.6570,
        "lng": 104.0800,
        "motion_template_id": "T08_Bokeh",
        "pony": False,
    },
    {
        "title": "给未来的我",
        "audio_text": "如果你听到这句，说明你又走过一年。",
        "mood_code": "emo",
        "lat": 30.6570,
        "lng": 104.0800,
        "motion_template_id": "T02_Cloud",
        "pony": True,
    },
    # Point B（九眼桥附近）30.6395, 104.0920
    {
        "title": "桥上有风",
        "audio_text": "风把情绪吹散一点点，我就当它在帮我。",
        "mood_code": "healing",
        "lat": 30.6395,
        "lng": 104.0920,
        "motion_template_id": "T06_Wind",
        "pony": False,
    },
    {
        "title": "今晚不想回消息",
        "audio_text": "我只想安静一下，明天再做决定。",
        "mood_code": "tired",
        "lat": 30.6395,
        "lng": 104.0920,
        "motion_template_id": "T08_Bokeh",
        "pony": False,
    },
    {
        "title": "笑一下就好",
        "audio_text": "没发生什么好事，但我决定先笑一下。",
        "mood_code": "light",
        "lat": 30.6395,
        "lng": 104.0920,
        "motion_template_id": "T07_Sparkle",
        "pony": False,
    },
    {
        "title": "马年祈福",
        "audio_text": "愿你像小马一样，轻轻跳过难关。",
        "mood_code": "luck",
        "lat": 30.6395,
        "lng": 104.0920,
        "motion_template_id": "T07_Sparkle",
        "pony": True,
    },
    # Point C（人民公园）30.6602, 104.0659
    {
        "title": "坐一会儿",
        "audio_text": "树影晃来晃去，我突然不想赶路了。",
        "mood_code": "healing",
        "lat": 30.6602,
        "lng": 104.0659,
        "motion_template_id": "T02_Cloud",
        "pony": False,
    },
    {
        "title": "别急",
        "audio_text": "你看，水面都不急，我们也别急。",
        "mood_code": "healing",
        "lat": 30.6602,
        "lng": 104.0659,
        "motion_template_id": "T01_Wave",
        "pony": False,
    },
    {
        "title": "今天还算可以",
        "audio_text": "虽然也累，但至少我还在往前走。",
        "mood_code": "light",
        "lat": 30.6602,
        "lng": 104.0659,
        "motion_template_id": "T08_Bokeh",
        "pony": False,
    },
    {
        "title": "留给明年（马年）",
        "audio_text": "明年再听的时候，希望你更轻松一点。",
        "mood_code": "emo",
        "lat": 30.6602,
        "lng": 104.0659,
        "motion_template_id": "T02_Cloud",
        "pony": True,
    },
    # Point D（宽窄巷子）30.6708, 104.0517
    {
        "title": "巷子里的灯",
        "audio_text": "灯光一亮，好像心也亮了一点。",
        "mood_code": "luck",
        "lat": 30.6708,
        "lng": 104.0517,
        "motion_template_id": "T03_Neon",
        "pony": False,
    },
    {
        "title": "我不想社交",
        "audio_text": "我不是讨厌谁，我只是需要充电。",
        "mood_code": "tired",
        "lat": 30.6708,
        "lng": 104.0517,
        "motion_template_id": "T08_Bokeh",
        "pony": False,
    },
    {
        "title": "慢慢走就好",
        "audio_text": "别催自己，别催别人，慢点就赢了。",
        "mood_code": "healing",
        "lat": 30.6708,
        "lng": 104.0517,
        "motion_template_id": "T06_Wind",
        "pony": False,
    },
    {
        "title": "马年好运",
        "audio_text": "愿你抬头见喜，低头见福。",
        "mood_code": "luck",
        "lat": 30.6708,
        "lng": 104.0517,
        "motion_template_id": "T07_Sparkle",
        "pony": True,
    },
    # Point E（东郊记忆）30.6679, 104.1227
    {
        "title": "今天的我有点酷",
        "audio_text": "我也不知道为什么，但我觉得自己还不错。",
        "mood_code": "light",
        "lat": 30.6679,
        "lng": 104.1227,
        "motion_template_id": "T04_LightLeak",
        "pony": False,
    },
    {
        "title": "想换个节奏",
        "audio_text": "如果生活太吵，我就换个频道。",
        "mood_code": "healing",
        "lat": 30.6679,
        "lng": 104.1227,
        "motion_template_id": "T02_Cloud",
        "pony": False,
    },
    {
        "title": "给自己一个拥抱",
        "audio_text": "你已经做得够多了，真的。",
        "mood_code": "tired",
        "lat": 30.6679,
        "lng": 104.1227,
        "motion_template_id": "T08_Bokeh",
        "pony": False,
    },
    {
        "title": "小马来啦",
        "audio_text": "马年第一句：别怕，你会越来越好。",
        "mood_code": "healing",
        "lat": 30.6679,
        "lng": 104.1227,
        "motion_template_id": "T07_Sparkle",
        "pony": True,
    },
    # Point F（天府广场）30.6574, 104.0665
    {
        "title": "人好多",
        "audio_text": "人好多，但我还是觉得有点孤单。",
        "mood_code": "emo",
        "lat": 30.6574,
        "lng": 104.0665,
        "motion_template_id": "T08_Bokeh",
        "pony": False,
    },
    {
        "title": "不说也行",
        "audio_text": "说不出来就算了，先呼吸一下。",
        "mood_code": "healing",
        "lat": 30.6574,
        "lng": 104.0665,
        "motion_template_id": "T02_Cloud",
        "pony": False,
    },
    {
        "title": "我会好起来的",
        "audio_text": "不是鸡汤，是我真的相信。",
        "mood_code": "light",
        "lat": 30.6574,
        "lng": 104.0665,
        "motion_template_id": "T07_Sparkle",
        "pony": False,
    },
    {
        "title": "马年愿望",
        "audio_text": "愿你每一次回头，都能看见自己成长。",
        "mood_code": "luck",
        "lat": 30.6574,
        "lng": 104.0665,
        "motion_template_id": "T07_Sparkle",
        "pony": True,
    },
    # Point G（科华北路）30.6310, 104.0720
    {
        "title": "下班路上",
        "audio_text": "我走得很慢，但我在回家。",
        "mood_code": "tired",
        "lat": 30.6310,
        "lng": 104.0720,
        "motion_template_id": "T08_Bokeh",
        "pony": False,
    },
    {
        "title": "一口气",
        "audio_text": "把这一口气吐出来，就轻一点。",
        "mood_code": "healing",
        "lat": 30.6310,
        "lng": 104.0720,
        "motion_template_id": "T06_Wind",
        "pony": False,
    },
    # Point H（望江楼公园）30.6298, 104.0971
    {
        "title": "河边的安静",
        "audio_text": "今天不想争，只想安静。",
        "mood_code": "healing",
        "lat": 30.6298,
        "lng": 104.0971,
        "motion_template_id": "T01_Wave",
        "pony": False,
    },
    {
        "title": "给未来的你（马年）",
        "audio_text": "如果你听到这句，记得夸夸自己。",
        "mood_code": "luck",
        "lat": 30.6298,
        "lng": 104.0971,
        "motion_template_id": "T07_Sparkle",
        "pony": True,
    },
]


def build_seed_payloads() -> List[Dict[str, object]]:
    base_photo = "https://example.com/assets/photo_"
    base_audio = "https://example.com/assets/audio_"
    return [
        {
            **moment,
            "photo_url": f"{base_photo}{index + 1:02d}.jpg",
            "audio_url": f"{base_audio}{index + 1:02d}.mp3",
            "mp4_url": None,
            "thumb_url": None,
            "duration_s": 4.0,
            "visibility": "public_anonymous",
            "zone_name": "成都",
            "radius_m": 3000,
        }
        for index, moment in enumerate(SEED_MOMENTS)
    ]
